alter table public.opportunities
  add column if not exists fetched_at timestamptz not null default now();

update public.opportunities
set category = case
  when category in ('Destek Programı', 'Fon Çağrısı')
    then 'Ulusal Destek ve Fonlar'
  when category = 'Yatırım'
    then 'Yatırım ve Sermaye Ağları'
  when category in ('Hızlandırma', 'Kuluçka', 'Etkinlik')
    then 'Etkinlik ve Programlar'
  when category in ('Haber', 'Sosyal Akış')
    then 'Haber ve Sosyal Medya Akışı'
  else category
end;

alter table public.opportunities
  drop constraint if exists opportunities_category_check;

alter table public.opportunities
  add constraint opportunities_category_check check (
    category in (
      'Ulusal Destek ve Fonlar',
      'Uluslararası Fonlar',
      'Yatırım ve Sermaye Ağları',
      'Etkinlik ve Programlar',
      'Haber ve Sosyal Medya Akışı'
    )
  );

create table if not exists public.ingestion_runs (
  id uuid primary key default gen_random_uuid(),
  trigger text not null check (trigger in ('manual', 'cron')),
  status text not null check (status in ('running', 'success', 'partial', 'failed')),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  collected_count integer not null default 0,
  inserted_count integer not null default 0,
  updated_count integer not null default 0,
  skipped_count integer not null default 0,
  error_count integer not null default 0
);

create table if not exists public.ingestion_logs (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.ingestion_runs(id) on delete cascade,
  source_id text not null,
  source_name text not null,
  source_kind text not null check (source_kind in ('rss', 'html', 'api')),
  status text not null check (status in ('success', 'error', 'skipped')),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  duration_ms integer not null default 0,
  collected_count integer not null default 0,
  inserted_count integer not null default 0,
  updated_count integer not null default 0,
  skipped_count integer not null default 0,
  error_message text,
  created_at timestamptz not null default now()
);

create index if not exists ingestion_runs_started_at_idx
  on public.ingestion_runs (started_at desc);

create index if not exists ingestion_logs_run_id_idx
  on public.ingestion_logs (run_id);

alter table public.ingestion_runs enable row level security;
alter table public.ingestion_logs enable row level security;
